#!/bin/bash
echo -e ""
echo -e "«» menu        : Menampilkan Daftar Perintah"
echo -e "«» user-add    : Membuat Akun SSH & OpenVPN"
echo -e "«» trial       : Membuat Akun Trial"
echo -e "«» user-del    : Menghapus Akun SSH & OpenVPN"
echo -e "«» user-login  : Cek User Login"
echo -e "«» user-list   : Daftar Member SSH & OpenVPN"
echo -e "«» expdel      : Delete User expired"
echo -e "«» resvis      : Restart Service Dropbear, Webmin"
echo -e "                 Squid3, OpenVPN,Stunnel & SSH"
echo -e "«» reboot      : Reboot VPS"
echo -e "«» speedtest   : Speedtest VPS"
echo -e "«» info        : Menampilkan Informasi Sistem"
echo -e "«» about       : Info Script Auto Install"
echo -e "«» exit        : Keluar Terminal"
